---
abstract: 'Monitor a directory structure for changes'
author:
  - 'Andy Grundman <andy@hybridized.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120630'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mac-FSEvents
no_index:
  directory:
    - t
    - inc
  file:
    - MacVersion.pm
requires: {}
version: 0.07
