---
abstract: 'Monitor a directory structure for changes'
author:
  - 'Andy Grundman <andy@hybridized.org>, Rob Hoelz <rob@hoelz.ro>'
build_requires:
  Cwd: '0'
  ExtUtils::MakeMaker: '0'
  File::Path: '0'
  File::Spec: '0'
  File::Temp: '0'
  IO::Select: '0'
  Scalar::Util: '0'
  Test::More: '0.99'
  autodie: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.24, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mac-FSEvents
no_index:
  directory:
    - t
    - inc
requires:
  Exporter: '0'
  base: '0'
  perl: '5.008008'
  strict: '0'
  warnings: '0'
resources:
  repository: https://github.com/hoelzro/Mac-FSEvents
version: '0.14'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
